# Generated by Django 3.0.3 on 2020-03-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_comment_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='for_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blogapp.Post'),
        ),
    ]
